name: ${snakeCaseName}
description: A new Flutter project run with flutter 3.24.x.
publish_to: 'none' # Dont Remove this !!!

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  baseX:
    git: 
      url: https://github.com/haolun1996/baseX.git
      ref: 0.2.8
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  faker: ^2.2.0

  # ===-===-=== Add new plugin below this line ===-===-===
  # firebase_core: ^3.1.1
  # firebase_messaging: ^15.0.2

# ===-===-=== Auto generation icon ===-===-===> flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 23

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: fonts/Lato-Regular.ttf
  #       - asset: fonts/Lato-Regular.ttf
  #         weight: 600
  #       - asset: fonts/Lato-Bold.ttf
  #         weight: 700